"""create table

Revision ID: 60bbfad1bc8f
Revises: 
Create Date: 2021-11-20 17:14:35.962074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bbfad1bc8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('title', sa.String(), server_default='blank', nullable=True))
    op.drop_column('notes', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('notes', 'title')
    # ### end Alembic commands ###
